In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# GALAXY DATASET

In [2]:
galaxy = pd.read_csv('COMBO17.csv')
galaxy

,Nr,Rmag,e.Rmag,ApDRmag,mumax,Mcz,e.Mcz,MCzml,chi2red,UjMAG,...,UFS,e.UFS,BFS,e.BFS,VFD,e.VFD,RFS,e.RFS,IFD,e.IFD
0,6,24.995,0.097,0.935,24.214,0.832,0.036,1.400,0.64,-17.67,...,0.01870,0.00239,0.01630,0.001290,0.017300,0.00141,0.01650,0.000434,0.02470,0.00483
1,9,25.013,0.181,-0.135,25.303,0.927,0.122,0.864,0.41,-18.28,...,0.00706,0.00238,0.00420,0.001150,0.003930,0.00182,0.00723,0.000500,0.00973,0.00460
2,16,24.246,0.054,0.821,23.511,1.202,0.037,1.217,0.92,-19.75,...,0.01260,0.00184,0.01830,0.001150,0.018800,0.00167,0.02880,0.000655,0.05700,0.00465
3,21,25.203,0.128,0.639,24.948,0.912,0.177,0.776,0.39,-17.83,...,0.01410,0.00186,0.01180,0.001100,0.009670,0.00204,0.01050,0.000416,0.01340,0.00330
4,26,25.504,0.112,-1.588,24.934,0.848,0.067,1.330,1.45,-17.69,...,0.00514,0.00170,0.00102,0.001270,0.000039,0.00160,0.00139,0.000499,0.00590,0.00444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3457,9990,24.962,0.186,-0.113,25.189,0.960,0.190,0.951,0.89,-18.21,...,0.00643,0.00170,0.00361,0.001150,0.004890,0.00147,0.00625,0.000413,0.00987,0.00323
3458,9992,21.918,0.017,-0.562,23.063,0.770,0.031,0.766,0.90,-20.47,...,0.03700,0.00218,0.04500,0.001310,0.051300,0.00173,0.07210,0.000542,0.10200,0.00477
3459,9995,23.701,0.051,-0.437,24.053,0.775,0.121,1.330,0.60,-18.76,...,0.02050,0.00223,0.01850,0.001090,0.014500,0.00182,0.01580,0.000468,0.01860,0.00484
3460,9996,23.473,0.098,-1.114,25.075,0.926,0.087,0.870,1.01,-19.67,...,0.01150,0.00225,0.00809,0.001190,0.011400,0.00166,0.01070,0.000454,0.01930,0.00390
3461,9997,25.621,0.298,-0.224,25.488,0.968,0.139,0.957,1.13,-17.70,...,0.00387,0.00165,0.00315,0.000949,0.002470,0.00131,0.00317,0.000426,0.00746,0.00415

In [3]:
np.count_nonzero(galaxy, axis = 0)

array([3462, 3462, 3462, 3459, 3462, 3462, 3461, 3459, 3462, 3462, 3462,
       3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462,
       3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462,
       3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462,
       3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462,
       3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462, 3462])

# Descriptive Statistics

In [4]:
nRow, nCol = galaxy.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 3462 rows and 65 columns

In [5]:
galaxy.describe()

,Nr,Rmag,e.Rmag,ApDRmag,mumax,Mcz,e.Mcz,MCzml,chi2red,UjMAG,...,UFS,e.UFS,BFS,e.BFS,VFD,e.VFD,RFS,e.RFS,IFD,e.IFD
count,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,...,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000,3462.000000
mean,5099.237435,23.939266,0.106156,-0.190947,24.181846,0.728503,0.090381,0.770000,1.167392,-17.866005,...,0.015965,0.002003,0.021882,0.001174,0.029518,0.001682,0.039055,0.000479,0.048502,0.004043
std,2826.911998,1.435899,0.083147,0.452994,1.017225,0.319010,0.061970,0.375989,0.682852,1.965501,...,0.025359,0.000335,0.064187,0.000343,0.119034,0.000631,0.164048,0.000199,0.187690,0.001486
min,6.000000,16.572000,0.001000,-4.700000,18.112000,0.007000,0.000000,0.000000,0.140000,-23.210000,...,-0.002430,0.001510,-0.001040,0.000843,-0.001830,0.001180,0.000912,0.000368,0.000056,0.003040
25%,2661.250000,23.099000,0.039000,-0.425000,23.624250,0.519000,0.036000,0.502250,0.730000,-19.070000,...,0.006120,0.001770,0.005580,0.001020,0.005922,0.001420,0.006860,0.000427,0.011000,0.003450
50%,5158.500000,24.073500,0.080000,-0.141000,24.387500,0.810000,0.076500,0.826500,1.020000,-18.210000,...,0.010200,0.001930,0.010300,0.001110,0.011600,0.001570,0.014000,0.000451,0.019100,0.003780
75%,7493.500000,25.029750,0.160000,0.089000,24.957500,0.981750,0.141000,1.024750,1.440000,-17.300000,...,0.017600,0.002150,0.020075,0.001240,0.023600,0.001800,0.029700,0.000488,0.039100,0.004270
max,9997.000000,27.000000,0.311000,1.462000,25.833000,1.379000,0.233000,1.400000,11.910000,-7.910000,...,0.410000,0.006320,1.470000,0.008290,3.170000,0.015900,4.630000,0.006830,5.290000,0.045500

# Galaxy Brightness

# Galaxy Redshift Magnitudes

In [6]:
redshift_mags =galaxy[['Nr','Rmag', 'e.Rmag']]
redshift_mags.describe()

                Nr         Rmag       e.Rmag
count  3462.000000  3462.000000  3462.000000
mean   5099.237435    23.939266     0.106156
std    2826.911998     1.435899     0.083147
min       6.000000    16.572000     0.001000
25%    2661.250000    23.099000     0.039000
50%    5158.500000    24.073500     0.080000
75%    7493.500000    25.029750     0.160000
max    9997.000000    27.000000     0.311000

In [ ]:
plt.figure(figsize = (12,8))                                  #Setting size of the figure (12 - Width, 8 - Height)
sns.barplot("Nr","Rmag", "e.Rmag", data=redshift_mags) 
plt.title('Redshift Magnitudes and Errors')               #Title
plt.xlabel('Galaxy', fontsize=14)                     #Label for X axis
plt.ylabel('Redshift Magnitudes + Error', fontsize=12)              #Label for Y axis
plt.show()

In [ ]:
fig, axs = plt.subplots(1, 2, sharey=True, tight_layout=True)
x = galaxy[['Rmag']]
y = galaxy[['e.Rmag']]
axs[0].hist(x, bins=10)
axs[1].hist(y, bins=10)
plt.show()

In [ ]:
pd.plotting.scatter_matrix(redshift_mags, alpha=0.2)
plt.show()

# Galaxy Sizes

In [7]:
galaxy_size =galaxy[['Nr', 'ApDRmag', 'mumax']]
galaxy_size.describe()

                Nr      ApDRmag        mumax
count  3462.000000  3462.000000  3462.000000
mean   5099.237435    -0.190947    24.181846
std    2826.911998     0.452994     1.017225
min       6.000000    -4.700000    18.112000
25%    2661.250000    -0.425000    23.624250
50%    5158.500000    -0.141000    24.387500
75%    7493.500000     0.089000    24.957500
max    9997.000000     1.462000    25.833000

In [ ]:
#positive_mu = galaxy.loc[galaxy['mumax'] > 0]

galaxy.plot(y='mumax')
plt.title('Galaxy Sizes')               #Title
plt.xlabel('Galaxy', fontsize=14)                     #Label for X axis
plt.ylabel('MuMax Value', fontsize=12)              #Label for Y axis

plt.show()

In [ ]:
largest = galaxy['mumax'].nlargest(10)
largest

In [ ]:
smallest = galaxy['mumax'].nsmallest(10)
print(smallest)

In [ ]:
pd.plotting.scatter_matrix(galaxy_size, alpha=0.2)
plt.show()

# Redshift Estimates

In [ ]:
abs_mag =galaxy[['Nr', 'Mcz', 'e.Mcz', 'MCzml', 'chi2red']]
abs_mag.describe()

In [ ]:
abs_mag.hist(figsize=(18,18))
plt.show()

# Absolute Magnitudes

In [ ]:
#select only the colums showing observed brightness data

abs_mag =galaxy.loc[:,'UjMAG':'e.VbMAG']
abs_mag.describe()

In [ ]:
abs_mag_n =galaxy[['Nr','UjMAG','BjMAG','VjMAG', 'usMAG', 'gsMAG', 'rsMAG', 'UbMAG', 'BbMAG', 'VnMAG']]
abs_mag_n.describe()

In [ ]:
sns.violinplot(x="Nr", y="rsMAG", data=abs_mag_n)
plt.show()

In [ ]:
abs_mag_n.plot.scatter('Nr', 'UjMAG')

In [ ]:
abs_mag2 =galaxy[['UjMAG','BjMAG','VjMAG', 'usMAG', 'gsMAG', 'rsMAG', 'UbMAG', 'BbMAG', 'VnMAG']]
abs_mag2.plot.box(figsize=(12,12))
plt.show()

In [ ]:
abs_mag2.plot.box(figsize=(12,12))
plt.show()

In [ ]:
sns.violinplot(abs_mag2)
plt.show()

# Observed Brightnesses

In [ ]:
#Show descriptive statistics
obs_bright =galaxy.loc[:,'S280MAG':'e.W914FE']
obs_bright.describe()

In [ ]:
obs_bright2 =galaxy[['S280MAG','W420FE', 'W462FE', 'W485FD','W518FE', 'W571FS', 'W604FE', 'W646FD', 'W696FE', 'W753FE', 'W815FS', 'W856FD', 'W914FD', 'W914FE', 'UFS', 'BFS', 'VFD', 'IFD']]
obs_bright3 =galaxy[['W462FE', 'W485FD','W518FE', 'W571FS', 'W604FE', 'W646FD', 'W696FE', 'W753FE', 'W815FS', 'W856FD', 'W914FD', 'W914FE', 'UFS', 'BFS', 'VFD', 'IFD']]

obs_bright3.describe()

In [ ]:
#remove data points more tha 2 standard deviation away from the mean
bright_numeric = obs_bright3.select_dtypes([np.number]).columns.values #first, find only columns with numeric data
bright_1 = obs_bright3.loc[:,bright_numeric]

changed = bright_1.copy()
before = bright_1.copy()

total_changed = 0

#for loop for every column
for col in changed.columns:
    #find mean and std of the columns
    col_mean = changed[col].mean()
    col_std = changed[col].std()
    
    #perform outlier test: if abs(X-mean) > 2*std, then replace with mean
    changed.loc[(abs(changed[col] - col_mean)) > (1 * col_std),col] = col_mean
    
    #count number changed in the column. before the subtraction sign counts the number of rows in the column
    #after the subtraction sign use a boolean matrix. Checks to see which rows remained the same. Then adds
    #those rows that remained the same. Expect changes = 0 if no changes
    changes = before[col].count() - (before[col] == changed[col]).sum()
    
    #add changes for each row to the counter for total
    total_changed += changes

print(f'The number of outliers that were replaced with the mean is {total_changed}.')

In [ ]:
plt.figure(figsize = (20,20)) 
ax = sns.violinplot(data = obs_bright3)
plt.show()

In [ ]:
obs_bright.hist(figsize=(18,18))
plt.show()

# Photometric Correlation

In [ ]:

plt.figure(figsize = (12,8))
corrplot = sns.heatmap(galaxy.corr())
plt.show()

In [ ]:

plt.figure(figsize = (12,8))
corrplot = sns.heatmap(obs_bright3.corr())
plt.show()